version: '3.8'
services:
  dictionary-service:
    build:
      context: ./dictionary-service/dictionary-service-impl
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    networks:
      - my-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/dictionary_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres

  rating-service:
    build:
      context: ./rating-service/rating-service-impl
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    networks:
      - my-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/rating_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres

  weather-integrations:
    build:
      context: ./integrations/weather-integration-impl
      dockerfile: Dockerfile
    ports:
      - "8083:8080"
    networks:
      - my-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/weather_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres

  database:
    image: postgres:13
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
