spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/weather_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: weather-service
weather:
  api:
    key: b77c37b980ec46e8ac191315241705